config/routes.rb
Rails.application.routes.draw do
  
  resources :whiskeys do
    resource :comments, only: [:create]
  end

  resources :users
  resources :categories
end

app/models/category.rb
class Category < ActiveRecord::Base


  has_many :whiskey_categories
  has_many :whiskeys, through: :whiskey_categories

  


end

app/models/comment.rb
class Comment < ActiveRecord::Base

  validates :content, presence: true
  
  belongs_to :whiskey

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :posts
  has_many :comments

end

app/models/whiskey.rb
class Whiskey < ActiveRecord::Base

	validates :name, presence: true
  validates :description, presence: true

  has_many :comments

  has_many :whiskey_categories
  has_many :categories, through: :whiskey_categories

  mount_uploader :image, ImageUploader

  

end

app/models/whiskey_category.rb
class WhiskeyCategory < ActiveRecord::Base

  belongs_to :whiskey
  belongs_to :category

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index

    @categories = Category.all

  end

  def new

    @category = Category.new

  end

  def create

    attrs = params.require(:category).permit(:name)
    @category = Category.new(attrs)

    if @category.save
      redirect_to categories_path   
    else
      render :new
    end

  end

  def show

    @category = Category.find(params[:id])

  end

  def edit

    @category = Category.find(params[:id])

  end

  def update

    @category = Category.find(params[:id])
    attrs = params.require(:category).permit(:name)
    @category.update(attrs)

    redirect_to categories_path
  end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

 def create

    @whiskey = Whiskey.find(params[:whiskey_id])
    attrs = params.require(:comment).permit(:content).merge(whiskey_id: @whiskey.id)
    @comment = Comment.new(attrs)
    @comment.save
    redirect_to whiskey_path(@whiskey)

  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index

    @users = User.all
    
  end

  def new

    @user = User.new
    
  end

  def create

    attrs = params.require(:user).permit(:name, :email, :age)
    @user = User.new(attrs)

    @user.save
    redirect_to user_path(@user)
    
  end

  def show

    @current_user = User.find(params[:id])

  end

end

app/controllers/whiskeys_controller.rb
class WhiskeysController < ApplicationController  

  def index
    @whiskeys = Whiskey.all
    @whiskeys = Whiskey
      .order(created_at: :desc)
      .offset((page - 1) * per_page)
      .limit(per_page)

    @total_pages = (Whiskey.count / per_page.to_f).ceil

  end

  def new
    @whiskeys = Whiskey.new
  end

  def create

    attrs = params.require(:whiskey).permit(:name, :description, :style, :image, category_ids: [])
    @whiskeys = Whiskey.new(attrs)
    
    if @whiskeys.save
      redirect_to whiskey_path(@whiskeys)
    else
      render :new
    end
    
  end

  def edit

    @whiskeys = Whiskey.find(params[:id])
    
  end

  def show
    
    @whiskeys = Whiskey.find(params[:id])
    @comments = @whiskeys.comments
    @comment = @whiskeys.comments.build
    
  end

  def update

    @whiskeys = Whiskey.find(params[:id])
    attrs = params.require(:whiskey).permit(:name, :description, :style, :image, category_ids: [])
    
    if @whiskeys.update(attrs)
      redirect_to whiskey_path(@whiskeys)
    else
      render :edit
    end
    
  end
  private

    def per_page
      3
    end

    def page
      return 1 if !params[:page]

      params[:page].to_i
    end    



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/categories/_form.html.erb
<h1>Create A Category</h1>

<%= form_for category do |f| %>
	<%= f.label :name %>
	<br>
	<%= f.text_field :name %>
	<br>
	<%= f.submit %>
<% end %>

app/views/categories/edit.html.erb
<%= render 'form', category: @category %>

app/views/categories/index.html.erb
<h1>Category Index</h1>

<form action="/categories/new">
    <input type="submit" value="Add Your Own Category!" />
</form>


<% @categories.each do |cat| %>
	<p><%= cat.name %></p>
	<hr>
<% end %>

app/views/categories/new.html.erb
<%= render 'form', category: @category %>

app/views/categories/show.html.erb
<p><%= @category.name %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WhiskeyApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="topnav">
		<%= link_to "Home", whiskeys_path %>
		<%= link_to "Submit A Whiskey", '/whiskeys/new' %>
		<%= link_to "Categories", categories_path %>
</div>
		


<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for user do |f| %>
	<%= f.label :name %>
	<br>
	<%= f.text_field :name %>
	<br>
	<%= f.label :email %>
	<br>
	<%= f.text_field :email %>
	<br>
	<%= f.label :age %>
	<br>
	<%= f.text_field :age %>
	<br>
	<%= f.submit %>
<% end %>

app/views/users/new.html.erb
<%= render 'form', user: @user %>

app/views/users/show.html.erb
<p>Name: <%= @current_user.name %></p>	
<p>Email: <%= @current_user.email %></p>
<p>Age: <%= @current_user.age %></p>

app/views/whiskeys/_form.html.erb
<h1>Enter A Whiskey</h1>

<% if whiskey.errors.any? %>
	<h2>Errors!</h2>
		<ul>
			<% whiskey.errors.full_messages.each do |error| %>
				<li><%= error %></li>
			<% end %>
		</ul>
<% end %>

<%= form_for whiskey do |f| %>
	<%= f.label :name %>
	<br>
	<%= f.text_field :name %>
	<br>
	<%= f.label :description %>
	<br>
	<%= f.text_area :description, size: "60x12" %>
    <br>
    <%= f.label :style %>
	<br>
	<%= f.select :style, ['Irish', 'Japanese', 'Scotch', 'Bourbon', 'Rye']%>
    <br>
    <%= f.label :image %>
    <br>
    <%= f.file_field :image %>
    <br>
    <%= f.label :flavours %>
    <br>
    <%= f.collection_check_boxes(:category_ids, Category.all, :id, :name) do |cat|%>
    	<%= cat.label {cat.check_box() + cat.text } %>
    <%end%>
    <br>
	<%= f.submit %>
<% end %>

app/views/whiskeys/edit.html.erb
<%= render 'form', whiskey: @whiskeys %>

app/views/whiskeys/index.html.erb
<h1>Whiskey Index</h1>

<% @whiskeys.each do |whiskey| %>
	<h4><a href="whiskeys/<%= whiskey.id %>"><%= whiskey.name %></a></h4>
	<p><%= whiskey.description %></p>
	<hr>
<% end %>



<% (1..@total_pages).each do |page| %>
  <%= link_to("Page #{page} | ", whiskeys_path(page: page)) %>
<% end %>

app/views/whiskeys/new.html.erb
<%= render 'form', whiskey: @whiskeys %>

app/views/whiskeys/show.html.erb
<h2><%= @whiskeys.name %></h2>
<img src = "<%= @whiskeys.image %>"/>
<h4>Description</h4>
<p><%= @whiskeys.description %></p>
<p><b>Style: </b><%= @whiskeys.style %></p>


<%= form_for([@whiskeys, @comment]) do |f| %>
	<p>
		<%= f.label :Leave_A_Comment %>
		<br>
		<%= f.text_area :content %>

	</p>	

	<p>
		<%= f.submit %>
	</p>
<% end %>

<h3>Comments</h3>
	
	<% @comments.each do |comment| %>
		<p><%= comment.content %></p>
		<hr>
	<% end %>